language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
cache:
  directories:
    - vendor
    - "$HOME/.composer/cache"
services: mysql
env:
  matrix:
    - WP_VERSION=5.0 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
script:
  - composer test
