name: CI/CD for PHP Library

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        php: [ '7.2', '8.0', '8.1' ] # PHP versions to check.
        wp: [ '5.9', 'latest' ]
    name: UnitTest in WordPress ${{ matrix.wp }} and PHP ${{ matrix.php }}
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  phpcs:
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 7.2

  status-check:
    runs-on: ubuntu-latest
    name: Status Check
    needs: [ test, phpcs ]
    steps:
      - name: Display Status
        run: echo "All Green"
